{
 "title": "Kubescape Node-agent insights",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_agent",
    "label": "Node agent",
    "query": {
     "query": "label_values(up{job=\"node-agent\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Performance metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$node_agent\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"$node_agent\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "eBPF events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Exec events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "irate(node_agent_exec_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "irate(node_agent_open_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "irate(node_agent_network_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "irate(node_agent_dns_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "irate(node_agent_http_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capability events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "irate(node_agent_capability_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hardlink events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "irate(node_agent_hardlink_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "irate(node_agent_ebpf_event_failure_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ptrace events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "irate(node_agent_ptrace_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Io_uring events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "irate(node_agent_iouring_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RandomX events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "irate(node_agent_randomx_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSH events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "irate(node_agent_ssh_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Symlink events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "irate(node_agent_symlink_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syscall events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "irate(node_agent_syscall_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Container events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Container start event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "irate(node_agent_container_start_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container stop event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "irate(node_agent_container_stop_counter{pod=~\"$node_agent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}